CREATE TABLE expenses_cost_of_goods
(
    id          BIGSERIAL NOT NULL,
    expense_id  UUID DEFAULT UUID_GENERATE_V4(),
    product_id  BIGSERIAL REFERENCES products(id) ON DELETE CASCADE,
    description VARCHAR NOT NULL,
    amount      REAL,
    from_date   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
